### ISSUE TITLE
Fix click to zoom

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#55] opened 2014-04-10 13:28 UTC
The click to zoom function isn't working with the new base map.

**Comment by eschow** [comment] 2014-04-21 04:32
Added code (commented out) that finds polygon bounds and fits map to bounds, but there's a bug.

Currently, the polygon highlights on click, shows appropriate information and zooms the map to the bounds of the polygon. But then the poly loses highlight and another poly is highlighted (usually anacostia river or observatory circle). 

Haven't figured out how the code is triggering a second highlight function.

**Comment by nickmcclellan** [comment] 2014-04-23 18:29
I'm not seeing the second highlight function, but maybe it's not happening in Firefox? I'm fine with closing this issues if we can't reproduce the error. @jonroberts maybe you can investigate?

**Comment by akilism** [comment] 2014-04-26 02:38
I could reproduce this where zooming either with the map buttons or double clicking would cause two paths to end up highlighted. I refactored the code a bit and it seems to be working good now. Let me know if you guys are still seeing issues with it and I'll take another look. @nickmcclellan @eschow @bonnieok

**Closed as completed** 2014-05-01 19:18 UTC
Labels: bug, D3/Javascript
