### ISSUE TITLE
DC Quadrants

### ISSUE THREAD

**Issue by jeffgruber** [DCActionforChildren/dcaction#135] opened 2015-03-19 00:13 UTC
Superimpose quadrant map (see here: http://opendata.dc.gov/datasets/071aa9b40a1a4b38a938f8f5058068a8_11?uiTab=table&geometry=-77.213%2C38.838%2C-76.701%2C38.919)

**Comment by cmgiven** [comment] 2015-03-19 00:16
Dupe of #134.

**Closed as completed by cmgiven** 2015-03-19 00:16 UTC
Labels: duplicate
